from typing import Any

from pydantic import BaseModel, ConfigDict, field_validator


class CreateJiraIssueParameters(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    project_id_or_key: str
    issue_type_id: str
    summary: str
    description: dict[str, Any]
    execution_command_id: str
    comparison_id: str
    baseline_assessment_id: str
    proposed_assessment_id: str
    target_identifier: str

    @field_validator(
        "project_id_or_key",
        "issue_type_id",
        "summary",
        "execution_command_id",
        "comparison_id",
        "baseline_assessment_id",
        "proposed_assessment_id",
        "target_identifier",
    )
    @classmethod
    def require_nonempty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("value must be nonempty")
        return value


def jira_issue_description(
    *,
    business_summary: str,
    policy_changes: list[str],
    operational_impact: str,
    deterministic_reason: str,
    evidence: list[str],
    command_id: str,
    comparison_id: str,
    baseline_assessment_id: str,
    proposed_assessment_id: str,
    baseline_extraction_attempt_id: str,
    proposed_extraction_attempt_id: str,
) -> dict[str, Any]:
    content: list[dict[str, Any]] = []

    def heading(text: str) -> None:
        content.append({"type": "heading", "attrs": {"level": 2}, "content": [_text(text)]})

    def paragraph(text: str) -> None:
        content.append({"type": "paragraph", "content": [_text(text)]})

    def bullets(items: list[str]) -> None:
        content.append(
            {
                "type": "bulletList",
                "content": [
                    {
                        "type": "listItem",
                        "content": [{"type": "paragraph", "content": [_text(item)]}],
                    }
                    for item in items
                ],
            }
        )

    heading("Business summary")
    paragraph(business_summary)
    heading("Policy comparison")
    bullets(policy_changes or ["No material typed-rule differences were recorded."])
    heading("Operational impact")
    paragraph(operational_impact)
    heading("Deterministic reason")
    paragraph(deterministic_reason)
    heading("Evidence reviewed")
    bullets(evidence or ["No additional evidence summary was available."])
    heading("ChangeOps audit lineage")
    bullets(
        [
            f"Execution command: {command_id}",
            f"Policy comparison: {comparison_id}",
            f"Baseline assessment: {baseline_assessment_id}",
            f"Proposed assessment: {proposed_assessment_id}",
            f"Baseline accepted extraction: {baseline_extraction_attempt_id}",
            f"Proposed accepted extraction: {proposed_extraction_attempt_id}",
        ]
    )
    paragraph("Generated by ChangeOps after explicit human approval.")
    return {"type": "doc", "version": 1, "content": content}


def _text(value: str) -> dict[str, str]:
    return {"type": "text", "text": value}
