from collections.abc import Iterator

import pytest
from sqlalchemy import func, select

from changeops.adapters.jira import JiraAdapterError, JiraCloudAdapter, JiraIssueReceipt
from changeops.config import get_settings
from changeops.db.models import ExecutionResult, JiraExecutionDelivery, JiraIssue
from changeops.db.session import SessionLocal
from tests.integration.test_action_approval_api import REVIEWER_HEADERS
from tests.integration.test_execution_commands_api import ADMIN_HEADERS
from tests.integration.test_policy_comparisons_api import (
    ACTOR_HEADERS,
    _complete_both_policy_analyses,
)


@pytest.fixture(autouse=True)
def jira_configuration(monkeypatch) -> Iterator[None]:
    monkeypatch.setenv("JIRA_BASE_URL", "https://acme.atlassian.net")
    monkeypatch.setenv("JIRA_EMAIL", "operator@example.com")
    monkeypatch.setenv("JIRA_API_TOKEN", "test-token")
    monkeypatch.setenv("JIRA_PROJECT_ID_OR_KEY", "ECM")
    monkeypatch.setenv("JIRA_ISSUE_TYPE_ID", "10001")
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


def _prepared_jira_command(client) -> dict:
    baseline, proposed = _complete_both_policy_analyses(client)
    comparison = client.post(
        "/api/v1/policy-comparisons",
        headers=ACTOR_HEADERS,
        json={
            "baseline_policy_change_id": baseline["policy_change_id"],
            "proposed_policy_change_id": proposed["policy_change_id"],
        },
    )
    assert comparison.status_code == 201, comparison.text

    run = client.post(f"/api/v1/impact-assessments/{proposed['assessment_id']}/approval-run")
    assert run.status_code == 201, run.text
    workbench = client.get(f"/api/v1/action-approval-runs/{run.json()['id']}/workbench").json()
    remediation_count = 0
    for item in workbench["items"]:
        action = item["review"]["original_action"]
        approved = action["action_type"] == "operational_remediation"
        remediation_count += int(approved)
        response = client.post(
            f"/api/v1/action-reviews/{item['review']['id']}/decisions",
            headers=REVIEWER_HEADERS,
            json={
                "decision": "approved" if approved else "deferred",
                "rationale": "Create the approved operational task." if approved else "Deferred.",
            },
        )
        assert response.status_code == 201, response.text
    assert remediation_count == 1

    prepared = client.post(
        f"/api/v1/action-approval-runs/{run.json()['id']}/execution-commands",
        headers=ADMIN_HEADERS,
    )
    assert prepared.status_code == 201, prepared.text
    commands = prepared.json()["commands"]
    assert len(commands) == 1
    command = commands[0]
    assert command["system"] == "jira"
    assert command["operation"] == "create_issue"
    assert command["parameters"]["comparison_id"] == comparison.json()["id"]
    assert command["parameters"]["execution_command_id"] == command["id"]
    assert command["parameters"]["summary"] == "Update International Business Travel Policy"
    rendered = str(command["parameters"]["description"])
    assert "Business summary" in rendered
    assert (
        "Update the source policy document to reflect the approved revision effective "
        "October 1, 2026."
    ) in rendered
    assert (
        "The source policy document must reflect the approved policy change. "
        "(Reason: DOCUMENT_CONTAINS_CHANGED_POLICY)"
    ) in rendered
    assert (
        "International Business Travel Policy, version 1, published in Acme Knowledge"
    ) in rendered
    assert "Approved revision effective October 1, 2026" in rendered
    assert "Primary policy-document dependency requires an update" in rendered
    assert "document id:" not in rendered
    assert "{'effective_date':" not in rendered
    assert "Generated by ChangeOps after explicit human approval." in rendered
    return command


def test_jira_success_replay_and_immutable_history(client, monkeypatch) -> None:
    calls = 0

    def create_issue(self, parameters):
        nonlocal calls
        calls += 1
        return JiraIssueReceipt(
            issue_id="10101",
            issue_key="ECM-42",
            api_url="https://acme.atlassian.net/rest/api/3/issue/10101",
            browse_url="https://acme.atlassian.net/browse/ECM-42",
        )

    monkeypatch.setattr(JiraCloudAdapter, "create_issue", create_issue)
    command = _prepared_jira_command(client)
    url = f"/api/v1/execution-commands/{command['id']}/execute"

    first = client.post(url, headers=ADMIN_HEADERS)
    replay = client.post(url, headers=ADMIN_HEADERS)

    assert first.status_code == 201, first.text
    assert first.json()["status"] == "succeeded"
    assert first.json()["jira_issue"]["issue_key"] == "ECM-42"
    assert replay.status_code == 200
    assert replay.json()["status"] == "already_applied"
    assert replay.json()["jira_issue"]["id"] == first.json()["jira_issue"]["id"]
    assert calls == 1
    with SessionLocal() as session:
        assert session.scalar(select(func.count()).select_from(JiraIssue)) == 1
        assert session.scalar(select(func.count()).select_from(ExecutionResult)) == 2
        delivery = session.get(JiraExecutionDelivery, command["id"])
        assert delivery.state == "succeeded"


def test_ambiguous_jira_failure_is_never_resent(client, monkeypatch) -> None:
    calls = 0

    def unavailable(self, parameters):
        nonlocal calls
        calls += 1
        raise JiraAdapterError(
            "jira_unavailable",
            "Jira did not confirm issue creation.",
            definitive_no_side_effect=False,
        )

    monkeypatch.setattr(JiraCloudAdapter, "create_issue", unavailable)
    command = _prepared_jira_command(client)
    url = f"/api/v1/execution-commands/{command['id']}/execute"

    first = client.post(url, headers=ADMIN_HEADERS)
    repeated = client.post(url, headers=ADMIN_HEADERS)

    assert first.status_code == 503
    assert first.json()["detail"]["code"] == "jira_unavailable"
    assert repeated.status_code == 503
    assert repeated.json()["detail"]["code"] == "jira_delivery_outcome_unknown"
    assert calls == 1
    with SessionLocal() as session:
        assert session.scalar(select(func.count()).select_from(JiraIssue)) == 0
        assert session.scalar(select(func.count()).select_from(ExecutionResult)) == 2


def test_definitive_authentication_failure_can_be_retried_safely(client, monkeypatch) -> None:
    calls = 0

    def create_issue(self, parameters):
        nonlocal calls
        calls += 1
        if calls == 1:
            raise JiraAdapterError(
                "jira_authentication_failed",
                "Jira rejected authentication.",
                definitive_no_side_effect=True,
            )
        return JiraIssueReceipt(
            issue_id="20202",
            issue_key="ECM-43",
            api_url="https://acme.atlassian.net/rest/api/3/issue/20202",
            browse_url="https://acme.atlassian.net/browse/ECM-43",
        )

    monkeypatch.setattr(JiraCloudAdapter, "create_issue", create_issue)
    command = _prepared_jira_command(client)
    url = f"/api/v1/execution-commands/{command['id']}/execute"

    rejected = client.post(url, headers=ADMIN_HEADERS)
    succeeded = client.post(url, headers=ADMIN_HEADERS)

    assert rejected.status_code == 401
    assert rejected.json()["detail"]["code"] == "jira_authentication_failed"
    assert succeeded.status_code == 201
    assert succeeded.json()["jira_issue"]["issue_key"] == "ECM-43"
    assert calls == 2
