import io
import json
from urllib.error import HTTPError, URLError

import pytest

from changeops.adapters import jira
from changeops.adapters.jira import JiraAdapterError, JiraCloudAdapter
from changeops.domain.jira_execution import CreateJiraIssueParameters, jira_issue_description


def _parameters() -> CreateJiraIssueParameters:
    return CreateJiraIssueParameters(
        project_id_or_key="ECM",
        issue_type_id="10001",
        summary="Operational remediation: policy document",
        description=jira_issue_description(
            business_summary="Apply the approved revision.",
            policy_changes=["effective date: modified"],
            operational_impact="The policy document requires an update.",
            deterministic_reason="DOCUMENT_CONTAINS_CHANGED_POLICY",
            evidence=["International Business Travel Policy — version 1"],
            command_id="command-1",
            comparison_id="comparison-1",
            baseline_assessment_id="assessment-1",
            proposed_assessment_id="assessment-2",
            baseline_extraction_attempt_id="attempt-1",
            proposed_extraction_attempt_id="attempt-2",
        ),
        execution_command_id="command-1",
        comparison_id="comparison-1",
        baseline_assessment_id="assessment-1",
        proposed_assessment_id="assessment-2",
        target_identifier="document-policy",
    )


def test_issue_template_is_human_readable_adf_with_required_lineage() -> None:
    description = _parameters().description
    rendered = json.dumps(description)

    assert description["type"] == "doc"
    assert description["version"] == 1
    assert "Business summary" in rendered
    assert "Policy comparison" in rendered
    assert "Operational impact" in rendered
    assert "Deterministic reason" in rendered
    assert "Evidence reviewed" in rendered
    assert "Execution command: command-1" in rendered
    assert "Generated by ChangeOps after explicit human approval." in rendered


def test_adapter_posts_one_task_and_returns_receipt(monkeypatch) -> None:
    captured = {}

    class Response:
        status = 201

        def __enter__(self):
            return self

        def __exit__(self, *args):
            return None

        def read(self):
            return b'{"id":"101","key":"ECM-7","self":"https://acme.atlassian.net/api/101"}'

    def fake_urlopen(request, timeout):
        captured["request"] = request
        captured["timeout"] = timeout
        return Response()

    monkeypatch.setattr(jira, "urlopen", fake_urlopen)
    receipt = JiraCloudAdapter(
        base_url="https://acme.atlassian.net",
        email="operator@example.com",
        api_token="secret",
        timeout_seconds=4,
    ).create_issue(_parameters())

    payload = json.loads(captured["request"].data)
    assert captured["request"].full_url.endswith("/rest/api/3/issue")
    assert captured["timeout"] == 4
    assert payload["fields"]["project"] == {"key": "ECM"}
    assert payload["fields"]["issuetype"] == {"id": "10001"}
    assert payload["fields"]["description"]["type"] == "doc"
    assert payload["properties"][0]["value"]["execution_command_id"] == "command-1"
    assert receipt.issue_key == "ECM-7"
    assert receipt.browse_url == "https://acme.atlassian.net/browse/ECM-7"


@pytest.mark.parametrize(
    ("status", "code", "definitive"),
    [
        (401, "jira_authentication_failed", True),
        (400, "jira_validation_failed", True),
        (503, "jira_unavailable", False),
    ],
)
def test_adapter_classifies_http_failures(monkeypatch, status, code, definitive) -> None:
    monkeypatch.setattr(
        jira,
        "urlopen",
        lambda *args, **kwargs: (_ for _ in ()).throw(
            HTTPError("url", status, "error", {}, io.BytesIO(b"{}"))
        ),
    )
    with pytest.raises(JiraAdapterError) as captured:
        JiraCloudAdapter(
            base_url="https://acme.atlassian.net",
            email="operator@example.com",
            api_token="secret",
            timeout_seconds=4,
        ).create_issue(_parameters())
    assert captured.value.code == code
    assert captured.value.definitive_no_side_effect is definitive


def test_adapter_treats_network_loss_as_ambiguous(monkeypatch) -> None:
    monkeypatch.setattr(
        jira,
        "urlopen",
        lambda *args, **kwargs: (_ for _ in ()).throw(URLError("lost")),
    )
    with pytest.raises(JiraAdapterError) as captured:
        JiraCloudAdapter(
            base_url="https://acme.atlassian.net",
            email="operator@example.com",
            api_token="secret",
            timeout_seconds=4,
        ).create_issue(_parameters())
    assert captured.value.code == "jira_unavailable"
    assert captured.value.definitive_no_side_effect is False
